theme: jekyll-theme-minimal

title: [KHelse Håndbok]
description: [Veiledning for å bruke og vedlikeholde pakker og funksjoner i KHelse]
logo: /img/logo.jpeg

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/helseprofil
